### ISSUE TITLE
How do I'll set an command what will be executed when click on the npc?

### ISSUE THREAD

**Issue by m-svob** [SzilBalazs/SimpleNPC#10]

**Comment by SzilBalazs** [comment]
Hi!
1. First create the NPC with /npc create {id}
2. After that you can /npc edit {id}
3. Here you can left click the paper called NPC command (or something like that) and follow the instruction in chat.
(Optional) 4. You can also edit it in the config file.

**Comment by SzilBalazs** [comment]
@sochas43

**Comment by SzilBalazs** [comment]
Closed because of inactivity.
