### ISSUE TITLE
Problems with World teleporting

### ISSUE THREAD

**Issue by ghost** [SzilBalazs/SimpleNPC#2]
Most of the time when i go to the edit mode and press on the NPC it works but when i click on World teleporting into the left click right click menu i click on any, but it doesnt ask me for the World name

**Comment by SzilBalazs** [comment]
Thanks, i think i know where is the problem i will try to fix it soon as i can.

**Comment by SzilBalazs** [comment]
https://www.mediafire.com/file/6m96mczpop0vts4/SimpleNPC.jar/file try this please. Is it working for you?
Edit: there is an error, im working on it.

**Comment by SzilBalazs** [comment]
In the latest release everything is fixed.
