### ISSUE TITLE
Delete Tab bug

### ISSUE THREAD

**Issue by Zan1456** [SzilBalazs/SimpleNPC#3]
I deleted all the npc but still see it on the tab

(Töröltem az összes npc-t de mégis látom a tab-en)

**Comment by SzilBalazs** [comment]
Try to /npc reload

**Comment by Zan1456** [comment]
Nothing changes with / npc reload. A server restart solves it, but that's not so normal, I think.

(Az /npc reload-nál semmi sem változik. Egy szerver restart megoldja, de ez nem annyira normális, szerintem.)

**Comment by SzilBalazs** [comment]
Is it stil bugged in 2.4? Edit: nvm i see the problem.

**Comment by SzilBalazs** [comment]
It seems to this is a Minecraft Client bug but i'm not sure

**Comment by SzilBalazs** [comment]
Ok so you have to /reload not /npc reload in the latest release.
