### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Zarkness2** [SzilBalazs/SimpleNPC#5]
My question is about if you plan to add support in the future to versions like 1.12 or so and you plan to add a system that you need a permission to see the npc and be at a certain distance to see the npc?

**Comment by SzilBalazs** [comment]
1. Version support: i'm not planning it in the near future
2. Sure! I will try to implement it today or tomorrow, thanks for the suggestion!

**Comment by Zarkness2** [comment]
Why don't you want to add support for older versions, mostly because I would like to use your plugin on my 1.12 server.

and thanks for adding the idea of needing x permission to see the npc and be at a certain distance from it I hope the distance is customizable.

**Comment by SzilBalazs** [comment]
Permission to see NPC is already done (you can downloadit from spigot), i will try to do the distance stuff tomorrow. Sorry, but i can't add support for more minecraft version because i have to specify a "root" to a vanilla minecarft server class for every version and it's really hard.

**Comment by Zarkness2** [comment]
lol how fast, about the distance no problem and about the version if it is difficult then I understand that you do not want to add it, I will have to use citizen for the lobby of my network that is 1.12.2 and I wanted to use the distance option in the lobby but well, I will use it in my skyblock that is 1.16.

**Comment by SzilBalazs** [comment]
I can make you a private 1.12.2 version if you need it.

**Comment by Zarkness2** [comment]
one question, why would you make a version with 1.12.2 private support and you don't want to add it to the public plugin? and by the way the plugin has a sound to play when you click on the npc? if it doesn't, could you add it? another thing the plugin has api? and if it doesn't, do you plan to create its own api, so you can tell the other devs of the plugins I use to add support?

**Comment by Zarkness2** [comment]
on the subject of version support I only say to support 1.12 and 1.16, the plugin works completely by packet? and you could add support for rgb/hexadecim colors.

**Comment by SzilBalazs** [comment]
1. I have to make a diffrent  .jar for every supported minecraft version and if i want to make it public it became a lot more complicated to make any new feature
2. How to make a NPC click sound: make a datapack with one function and place a playsound and a command that you want to run inside this function
3. If the api only used for version suppott no, but if i want to implement a trait system like in citizens i will make one. 
4. Its mostly packets
5. I'm not sure that minecraft supports that, i will look into it.

**Comment by Zarkness2** [comment]
> 1. I have to make a diffrent  .jar for every supported minecraft version and if i want to make it public it became a lot more complicated to make any new feature
> 2. How to make a NPC click sound: make a datapack with one function and place a playsound and a command that you want to run inside this function
> 3. If the api only used for version suppott no, but if i want to implement a trait system like in citizens i will make one.
> 4. Its mostly packets
> 5. I'm not sure that minecraft supports that, i will look into it.


1. if you have to make a different .jar for each supported version then it's ok not to have 1.12 support
2. can't you make a command like citizen has for the sounds? that would be easier and faster, the citizen command is something like `/npc sound (--death [death sound/d]) (--ambient [ambient sound/d]) (--hurt [hurt sound/d]) (-n(one)/-s(ilent)) (-d(efault)) Sets an NPC's played sounds`  why don't you add a command like that?
3. The api of a plugin is so that other devs can give support in their plugins to yours, is that without api so that other devs can add compatibility to yours I will not be able to use it for much on my servers
4. if it is all packets I like it a lot and it will help me a lot in the optimization of the npc's theme.
5. minecraft added support for hexadecimal/rgb colors in version 1.16 so yes it is compatible with those colors.

another thing in your plugin can i set the npc to be a mob instead of a player?

**Comment by SzilBalazs** [comment]
0. Sorry but with this distance feature tps is halfed and with this super low performance i don't think i want to release it.
1. -
2. I will try to implement that
3. I know, but just ask me and i give you permission to modify my code
5. If i know it correctly Entity's name not support rbg, but with chat you can use the tellraw commands
6. Sorry, but if you want mob "NPC" just use Citizens, it has lot more feature than this.

**Comment by Zarkness** [comment]
okay, thank you very much

**Comment by Zarkness2** [comment]
Thank you very much, but I don't think I will end up using your plugin as it lacks a lot of things, which you could add but it seems you don't want to implement, good luck.

**Comment by SzilBalazs** [comment]
With this plugin i wanted learn usage of packets. I never wanted to replace bigger NPC plugins like citizens.

**Comment by SzilBalazs** [comment]
I hope the best for your server

**Comment by Zarkness2** [comment]
thanks and still learning about packets, if you were not thinking of competing with citizens why did you upload the plugin to spigot?

**Comment by SzilBalazs** [comment]
I wanted to create a fast and simple way to create NPCs, this is why its "Simple"NPC.

**Comment by Zarkness2** [comment]
a ok, well, good luck learning how to use packets in minecraft

**Comment by SzilBalazs** [comment]
Thank you!
